---
ansible_user_dir: "{{ lookup('env', 'HOME') }}"
cifmw_installyamls_repos: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/install_yamls"

# edpm_prepare role vars
cifmw_operator_build_meta_name: "openstack-operator"
cifmw_edpm_prepare_skip_crc_storage_creation: true


# openshift_login role vars
cifmw_openshift_user: "kubeadmin"
cifmw_openshift_password: "123456789"
cifmw_openshift_api: api.crc.testing:6443
cifmw_openshift_kubeconfig: "{{ ansible_user_dir }}/.kube/config"
cifmw_openshift_skip_tls_verify: true
cifmw_config_certmanager: true

pre_infra:
  - name: Download needed tools
    inventory: 'localhost,'
    connection: local
    type: playbook
    source: "{{ cifmw_installyamls_repos }}/devsetup/download_tools.yaml"

post_ctlplane_deploy:
  - name: Tune rabbitmq resources
    type: playbook
    source: rabbitmq_tuning.yml

  - name: Validate podified control plane
    type: playbook
    source: validate_podified_deployment.yml
    extra_vars:
      podified_validation: "{{ podified_validation | default ('false') | bool }}"
      cifmw_openshift_kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
      cifmw_path: "{{ cifmw_path }}"
      openstack_namespace: "{{ cifmw_install_yamls_defaults['NAMESPACE'] }}"

cifmw_install_yamls_vars:
  DEPLOY_DIR: "{{ cifmw_basedir }}/artifacts/edpm_compute" # used during Baremetal deployment
  INFRA_REPO: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/infra-operator"
  BMAAS_INSTANCE_MEMORY: 8192
  BMAAS_INSTANCE_VCPUS: 6
  BMAAS_INSTANCE_DISK_SIZE: 40
  DATAPLANE_GROWVOLS_ARGS: "/=8GB /tmp=1GB /home=1GB /var=8GB"
  DATAPLANE_TOTAL_NODES: 2
  INSTALL_CERT_MANAGER: false
  BMO_SETUP_ROUTE_REPLACE: false

cifmw_use_crc: false
cifmw_use_libvirt: false


# Deploy EDPM in multinode scenario
cifmw_deploy_edpm: true

post_infra: &fetch_nodes_facts
  - name: Fetch nodes facts and save them as parameters
    type: playbook
    inventory: "{{ ansible_user_dir }}/ci-framework-data/artifacts/zuul_inventory.yml"
    source: fetch_compute_facts.yml

pre_update: *fetch_nodes_facts

cifmw_openshift_setup_skip_internal_registry_tls_verify: true
# openshift_setup role vars
cifmw_openshift_setup_skip_internal_registry: true


# edpm_deploy role vars
cifmw_baremetal_hypervisor_target: baremetal-hypervisor # remove
cifmw_sushy_emulator_hypervisor_target: baremetal-hypervisor
cifmw_edpm_deploy_baremetal: true

cifmw_libvirt_manager_configuration:
  vms:
    edpm-compute:
      amount: 2
      disk_file_name: "blank"
      disksize: 50
      memory: 8
      cpus: 4
      bootmenu_enable: "yes"
      nets:
        - public
        - provision
  networks:
    public: |-
      <network>
        <name>public</name>
        <forward mode='nat'/>
        <bridge name='public' stp='on' delay='0'/>
        <mac address='52:54:00:6a:f2:dc'/>
        <ip family='ipv4' address='192.168.100.1' prefix='24'>
          <dhcp>
            <range start='192.168.100.10' end='192.168.100.100'/>
          </dhcp>
        </ip>
      </network>
    provision: |-
      <network>
        <name>provision</name>
        <forward mode='passthrough'>
        <interface dev='eth10'/>
        <interface dev='eth11'/>
        <interface dev='eth12'/>
        <interface dev='eth13'/>
        <interface dev='eth14'/>
        </forward>
      </network>
